### ISSUE TITLE
Issue in Draggable slider

### ISSUE THREAD

**Issue by ssuryakumar** [extralagence/extra.slider#1]
I created a slider with draggable option and i found this issue bothering the quality. When i drag the image in one direction and immediately if i drag in opposite direction, the "draggable" is not getting triggered.

**Comment by jbjanot** [comment]
Yeah the slider waits for the movement to be finished, in order to prevent some position related bugs. Will see what I can do for you. Thanks for your feedback 😃

**Comment by jbjanot** [comment]
Hi ssuryakumar,

Well... it's been a long time since you opened this issue, but the last version now corrects this behaviour.
Please fell free to reopen it if something goes wrong ;)

Thanks !
