### ISSUE TITLE
Extra list items

### ISSUE THREAD

**Issue by MTAIan** [extralagence/extra.slider#11]
For some reason I get duplicate list items that hang below the wrapper and it won't center on my second or third actual list items.

**Comment by jbjanot** [comment]
Hi @MTAIan,

Was your problem due to something going wrong in the slider code ?

I'll be happy to fix it if it does.

**Comment by MTAIan** [comment]
I found a work around. I have to add this style, (<h3 style="transform: matrix(1, 0, 0, 1, 0, -480)”>) to all the list items after the first child, but it lead to a cool idea where I have titles in a different div move in synchronous with pictures in a separate div.

That lead to a separate question: is it easy (or even possible) to have multiple sliders on one page?

Ian Harper
Digital Artist
NYCT Corporate Communications
(646) 252-6841

**Comment by jbjanot** [comment]
You should have no particular problems to add multiple sliders in one page.
Are you trying to overlap and synchronyse them ?

**Comment by MTAIan** [comment]
I can synchronize them no problem, I was just wondering about having two run independently. I’ve seen some other sliders that allow you to just add a number at the end of the containing div like (class=“extra-slider1”), but it looks like with yours all I have to do is match the $(“.this”).extraSlider({… With whatever I want.

Ian Harper
Digital Artist
NYCT Corporate Communications
(646) 252-6841

**Comment by jbjanot** [comment]
Yes, it loops through all instances of the jquery selector you pass and make them behave independantly.

**Comment by MTAIan** [comment]
I have two questions. Is there a way to turn off the infinite loop? If there is, is there a way to hide the next button on the last slide and the prev button on the first slide?

I added this line of code to your extra.slider.js `$items.not(".extra-slider-clone").last().addClass("extra-slider-last");` but i'm not sure how to listen for when last gets the active tag.

**Comment by jbjanot** [comment]
Hi @MTAIan,

Sorry for the delayed answer.
I created a codepen here to show you how to do it : http://codepen.io/extralagence/pen/ONBBwm?editors=0010

Have a nice day !

**Comment by MTAIan** [comment]
Thanks.

Ian Harper
Digital Artist
NYCT Corporate Communications
(646) 252-6841
