### ISSUE TITLE
Auto-slider tablet issue

### ISSUE THREAD

**Issue by MTAIan** [extralagence/extra.slider#12]
I noticed on some tablets the auto-slider reads the mouse enter as the last place clicked. Like for example if the button to get to the gallery is in the same place as where the gallery loads in.

I was wondering if there was a way to change this to on click or mousemove auto-slider pauses for x amount of seconds then resumes regardless of where the cursor is?

**Comment by jbjanot** [comment]
Hey @MTAIan ,

Thanks for your feedback.
You are right, the pause / resume events are not flexible enough.
I edited the code to allow you to pass any event (click, mouseenter, etc...).
By default, the event triggered is mouseenter for pause and mouseleave for resume, but I made a codepen that works with click events (like a toggle mode).

Have a look at it here : http://codepen.io/extralagence/pen/MyPzoN

I am about to commit the changes in a few minutes.

Bye !

**Comment by MTAIan** [comment]
Cool. I’ll play with it after you commit the changes. I’m trying to get a settimeout function to fire after a mousedrag  on tablets so it doesn’t pause because the tablet is saying the mouse is in the frame.

Ian Harper
Digital Artist
NYCT Corporate Communications
(646) 252-6841

**Comment by jbjanot** [comment]
Hi @MTAIan 
I forgot to confirm you that I added custom events for autoplay and autopause.

The doc is up-to-date : http://slider.extralagence.com/documentation/

Bye !

**Comment by MTAIan** [comment]
Awesome, thanks.

Harper, Ian
Animator
2 Broadway
ian.harper@nyct.commailto:ian.harper@nyct.com

On May 9, 2016, at 04:14, Jean-Baptiste Janot <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @MTAIanhttps://github.com/MTAIan
I forgot to confirm you that I added custom events for autoplay and autopause.

The doc is up-to-date : http://slider.extralagence.com/documentation/

Bye !
