### ISSUE TITLE
Question about previewing next slide

### ISSUE THREAD

**Issue by clse** [extralagence/extra.slider#14]
Hi Jean Baptiste,

Fellow Frenchie here. I wanna build something using your slider. What I'm trying to do is on hover of next and prev arrows, I wish to have the next slide show up on the corresponding side as a preview. Is there an easy way for me to do so with your slider?

Basically, on hover of the next arrow, for example, the next slide will slide in half way from the right through the slider's area as a preview, and the same goes for the clicking on prev, except it will come in from the left.

I would really appreciate your response!

Merci beaucoup
Melissa

**Comment by jbjanot** [comment]
Hi Mélissa,

I might have an idea on how to do it.
Let me have a look later today, I'll try to make a quick codepen.

Bonne journée à plus tard :)

**Comment by clse** [comment]
Awesome! Thanks so much!

À plus tard !

**Comment by jbjanot** [comment]
Is this something like that that you want to achieve ? 

http://codepen.io/extralagence/pen/XKKZar

**Comment by clse** [comment]
Oui!!! Thanks so much. Thats perfect. I really appreciate it.

**Comment by clse** [comment]
Last quick question: Any way you could tweak that to keep the hover active while the cursor is on the $nextslide ? Thanks!

**Comment by jbjanot** [comment]
Sure just keep track of the hover state and relaunch it after the slider has moved : http://codepen.io/extralagence/pen/XKKZar?editors=0010

**Comment by clse** [comment]
Oh thanks, I meant, keep the preview active (the nextslide being over the current slide) while the cursor is on that preview area. Do you know what I mean? On hover next, the preview slides in, I'd like it to stay active as long as the cursor is on "next" or on the preview.

**Comment by jbjanot** [comment]
Do you mean on a larger area than the next and previous buttons ?
In this case, you will have to add a custom div used only for triggering mouse events, but doing the same stuff.

**Comment by clse** [comment]
I mean, once $nextslide has been moved in, as long as the cursor stays on the $nextslide preview area, I'd like for it to stay there. if that makes sense? almost as if $next and $nextslide provoked the mouseenter/mouseleave. Should I create a div that triggers the next slide to get previewed, and have that div also enlarge on hover to match the preview?

**Comment by jbjanot** [comment]
Ok, so yes the best way to do it would be to replace the mouseenter and mouseleave of the buttons by custom ones with two div above the slider (between the slider and the button actually). Or just simply extend the next and previous buttons and make them cover half the slider.

**Comment by clse** [comment]
Awesome! This has been so helpful, merci infiniment!

**Comment by jbjanot** [comment]
You're welcome Melissa, thanks for using the slider ;)

À la prochaine.
