### ISSUE TITLE
Running slide count

### ISSUE THREAD

**Issue by jrobertblack** [extralagence/extra.slider#15]
Is there a way to use have a running count  of slides, like "1/5", "2/5" and so on...

Wanted to disable the pagination buttons and have just this.  I think its pretty rare anyone actually clicks on those pagination circles. People don't open sliders and say oh I want number 5 image, then count the dots and try to click on the fifth tiny circle icon. Most people would just click on the arrow 5 times, think numbers are just more user friendly, but great slider and use of gsap...

**Comment by jbjanot** [comment]
Hey jrobertblack,

Sure you can !
Here is a little codepen I careffully crafted for you : http://codepen.io/extralagence/pen/rLwKbm

You can have a parameter to show the current slide in the pagination buttons (paginateContent).
And the counter on top of the slider can easily be achieved by listening to the "extra:slider:moveStart" event.

Hope that helps !
Thanks for the nice feedback ;)

**Comment by katalysis** [comment]
This doesn't seem to work any more - any chance of updating the codepen?
