### ISSUE TITLE
jQuery dependent.

### ISSUE THREAD

**Issue by RickSlijkhuis** [extralagence/extra.slider#17]
Hi it's such a big shame that this plugin is jQuery dependent. There are so many frameworks out there right now that do not need jQuery anymore for selecting elements. 

I consider this a small change in the plugin what will make it compatible for such a wider range of GSAP users that do not want to use jQuery anymore.

jQuery users can of course still use the plugin with this change.

**Comment by jbjanot** [comment]
Hi @RickSlijkhuis and thanks for the feedback

Well I guess I'll stick with beeing shameful, as I do not plan to make it jQuery independant.
Every projects I use still need jQuery, one way or another.

Feel free to fork it and propose a pull request, I'll be glad to merge it if it fits.

Have a nice day.
See you.
