### ISSUE TITLE
wrapper max width not respecting max image width

### ISSUE THREAD

**Issue by eighthday** [extralagence/extra.slider#3]
Great work, thank you! 

I have a little problem when my image is smaller than my column width, I see a bit of next slide:

![screen shot 2015-10-19 at 13 58 54](https://cloud.githubusercontent.com/assets/4104767/10578363/929a5b10-7669-11e5-8749-2fc6158bb138.png)

**Comment by jbjanot** [comment]
Hi heightday.

Thanks for the nice feedback ;)

Would you be able to share a link to your html page ?
My guess is that it must be a css related issue.

**Comment by eighthday** [comment]
thanks for the quick reply:

http://render.eighthday.modxcloud.com/projects/st-georges-day

**Comment by eighthday** [comment]
sorry fixed it! just need to set overflow hidden on the wrapper

**Comment by jbjanot** [comment]
;)

Or you could add this bit of code to fix the width and center the slider:

```
.rowBlock.slides {
    margin: 0 auto;
    width: 730px;
    max-width: 100%;
}
```

**Comment by eighthday** [comment]
my slideshows will have variable widths
