### ISSUE TITLE
Min drag ease

### ISSUE THREAD

**Issue by eighthday** [extralagence/extra.slider#4]
It would be very nice if when you drag within the min drag amount, the slider animates (using the ease option) back into place.

**Comment by jbjanot** [comment]
Hi again !

Indeed, that would be nice, I'll see what I can do.

I'll reply when I can have a look at it, thanks for the idea.

**Comment by jbjanot** [comment]
Hi eighthday,

This behaviour is not corrected in the last update.
Feel free to reply if something goes wrong :)

Thanks for the feedback.
