### ISSUE TITLE
Feature request: No slideshow functionality if only one image 

### ISSUE THREAD

**Issue by eighthday** [extralagence/extra.slider#6]

**Comment by jbjanot** [comment]
Mh, I guess this one could be done on your side.
Something like :

``` javascript
var $slider = $(".extra-slider");

if ($slider.find("li").length) {
    $slider.extraSlider();
}
```

Although I could handle it in the code directly, I guess some people might need to use the resize behaviour or such, so I'll keep it that way for now.

Is there a good reason for you that could justify to do it inside the plugin ?
