### ISSUE TITLE
Events are fired, but the slider is not changing slides on Chrome

### ISSUE THREAD

**Issue by panayotoff** [extralagence/extra.slider#7]
Hi guys,

I had some really weird bug. Sometimes on Chrome when I click on prev/next button, or on bullets nav, the bullets change, my event handlers for "update.extra.slider" are executed, but the slider stays on the same slide. When I drag and release it, it scrolls multiple slides to where it should be. 
I'm using GSAP 1.8.0 and latest version of Draggable on Chrome 46.0.2490.71 (64-bit) on OSX, with ExtraSlider 1.2 

Here is the behaviour ( I can't upload the files, because the project is still in private dev ) http://cloud.bassta.bg/extraslider.webm

[Slider behaviour webm link](http://cloud.bassta.bg/extraslider.webm)

**Comment by panayotoff** [comment]
UPDATE:
The problem seems to be at adjustPosition function;

The `totalWidth` var is `NaN`, which causes `left` var to be `NaN`, which causes TweenMax not applying proper initial transform

Code should be:

```
 function adjustPosition() {
                if (currentItem > total) {
                    // too far on the left (previous)
                    currentItem = 0;
                } else if (currentItem < 0) {
                    // too far on the right (next)
                    currentItem = total;
                }

                //FIX
                if (!totalWidth) {
                    totalWidth = singleWidth;
                }
                //End FIX 
                var left = -(totalWidth * (currentItem) + (numClones * singleWidth));
```

**Comment by jbjanot** [comment]
Hi panayotov,

Thanks for the feedback.
I don't really understand why this fix is needed...
To help you, I will need to have a look at the files. Any chance to reproduce this in a codepen or to put the website online ?

**Comment by jbjanot** [comment]
Hi,

I'll consider this one closed...
Thank you for your feedbacks.
